### ISSUE TITLE
TypeError: Cannot read property 'field' of undefined

### ISSUE THREAD

**Issue by uuf6429** [storyblok/wordpress-importer#5]
I'm getting the following error:
```
TypeError: Cannot read property 'field' of undefined
    at file:///.../node_modules/wp2storyblok/src/migration.js:348:184
    at Array.map (<anonymous>)
    at file:///.../node_modules/wp2storyblok/src/migration.js:346:52
```

```js
const field_name = typeof content_type.schema_mapping[taxonomy.field] === 'string' ? content_type.schema_mapping[taxonomy.field] : content_type.schema_mapping[taxonomy.field].field
```

Maybe the condition should be reversed to check for an object?
```js
const field_name = typeof content_type.schema_mapping[taxonomy.field] !== 'object' ? content_type.schema_mapping[taxonomy.field] : content_type.schema_mapping[taxonomy.field].field
```

----

PS: the "submit an issue" link seems to be broken: https://github.com/storyblok/wordpress-importer#support

**Comment by christianzoppi** [comment]
Hey @uuf6429, thanks for reporting this! I will have a look at better handling the error on this, but basically, if you get that error it means you didn't include in your mapping the field that you are using for your taxonomy, so you should add it also to the `schema_mapping`. So regardless of how the script is checking that, you should have that field in the mapping.

I've fixed the link for the issues, thank you!

**Comment by uuf6429** [comment]
Thanks!

I've been avoiding migrating taxonomies since it still isn't fully clear to me how this part works (which is also how I've avoid the error above). I'll revisit this later.
